### ISSUE TITLE
[Question]: use k8sGPT based on Azure openai platform meet unexpected error

### ISSUE THREAD

**Issue by WOODY-ALLEN** [k8sgpt-ai/k8sgpt#466] opened 2023-05-26 02:23 UTC
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [x] K8sGPT (CLI)
- [ ] K8sGPT Operator

### K8sGPT Version

v0.3.4

### Kubernetes Version

v1.23.9-eks-ba74326

### Host OS and its Version

Amazon Linux 2

### Steps to reproduce

1. Run `brew install k8sgpt`
2. Run `k8sgpt auth add --backend azureopenai --baseurl https://xxxxxx.openai.azure.com/    --engine xxxx  --model xxxx`
3. input secret
4.  Run` k8sgpt analyze --explain --namespace=xxxx --backend azureopenai`

### Expected behaviour

I expected that k8sgpt can run after step 4 ,but i met error.

### Actual behaviour

After step4, it showed like pic below.
<img width="840" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt/assets/42052823/44760adb-824e-4b8c-b8d8-8925e6c2eece">

**Comment by arbreezy** [comment] 2023-05-28 11:29
are you using an EKS cluster? @WOODY-ALLEN 

this looks familiar with a not so recent [issue](https://github.com/aws/aws-cli/issues/6920) with aws cli
error has to do with the way you configure your kube config file.

you can also specify a different kube config file with k8sgpt cli 
```--kubeconfig string    Path to a kubeconfig. Only required if out-of-cluster.```


what does this print `kubectl config view | grep 'client.authentication.k8s.io'` ?

**Comment by arbreezy** [comment] 2023-05-30 08:35
I think the issue is not relevant with the project itself, I am going to close the issue but feel free to reopen if you see it appropriate.

**Closed by arbreezy** 2023-05-30 08:35 UTC
